apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: demo-cicd-setup
  namespace: default
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - demo-cicd-setup
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-rh-hcas-emea-cluster-conf-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-rh-hcas-emea-cluster-conf
  namespace: ggithubcom-rh-hcas-emea-cluster-conf-ns
spec:
  type: Git
  pathname: 'https://github.com/rh-hcas-emea/cluster-config.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: clusters/demo-gitops-cicd/cluster-gitops
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: demo-cicd-setup
  name: demo-cicd-setup-subscription-1
  namespace: default
spec:
  allow:
  - apiVersion: argoproj.io/v1alpha1
    kinds:
    - ApplicationSet
  channel: ggithubcom-rh-hcas-emea-cluster-conf-ns/ggithubcom-rh-hcas-emea-cluster-conf
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-cicd-setup-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: demo-cicd-setup
  name: demo-cicd-setup-placement-1
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      'clusterGroup': 'demo-gitops-cicd'
